"""Versioned prompt templates."""

from prompts.templates import (
    REQUIREMENT_EXTRACTION_SYSTEM,
    REQUIREMENT_EXTRACTION_USER,
    REQUIREMENT_EXTRACTION_VERSION,
    RESUME_EXTRACTION_SYSTEM,
    RESUME_EXTRACTION_USER,
    RESUME_EXTRACTION_VERSION,
)

__all__ = [
    "REQUIREMENT_EXTRACTION_SYSTEM",
    "REQUIREMENT_EXTRACTION_USER",
    "REQUIREMENT_EXTRACTION_VERSION",
    "RESUME_EXTRACTION_SYSTEM",
    "RESUME_EXTRACTION_USER",
    "RESUME_EXTRACTION_VERSION",
]
